### ISSUE TITLE
The !Quote command

### ISSUE THREAD

**Issue by Compleatly** [mrphlip/lrrbot#102]
Greetings friends. In an effort to make the LoadingReadyRun sphere of influence a more comfortable, entertaining, exciting and overall positive space, I'd like to address one of the more recent issues some members of the "LoadingReadyLive!" Twitch community have had with LRRbot and its functionalities. 

I know that you all (Phlip, D3fr0st5 and Qrpth specifically) constantly deal with bloat in LRRbot's commands, determining which commands which should stay and which should be removed. Ever since Twistedpear introduce the quote function in his Patreon bot, Pump19, the chat has, overall, reacted positively to the opportunity, hence the porting of quotes on to LRRbot. 

However, as the months move by, some of the chat has voiced concern over the nature of the !Quote command. The general critique that its opponents appear to have is that in addition to being fairly spammy and disruptive when putting out a quote, especially for the larger, more elaborate ones, people- especially the random viewers who appear from time to time- repeatedly attempt to use the !quote command, further adding to the level of spam the chat faces.

I know you all have attempted to deal with the issue in the past via increasing the delay timer between !quote submissions and response, but I feel that this has not really solved the issue of people constantly using !Quote. Increasing the timer only delays the inevitable, while the issue of spam still remains. The quotes themselves can additionally be disruptive during downtimes in chat where there are no streams. Fans often linger in the chat and have conversations and discussions. The sudden appearance of 10-20 lines of text from crew members speaking out of turn can be very hostile to the stability of a calm conversation.

The next most logical step would be to remove !Quote entirely. As some of the chat have stated "commands like !death and !next are tools for the chat. !Quote is a toy.". I will admit that there is a bit of humour in looking through some of the older quotes that have long since lost their context and it can be a good diversion from time to time. Removing the !quote command would punish those who enjoy said diversion. In addition, typically the chat as a whole will never really ask for commands to be removed for LRRbot if they're as amusing as quote. In short, we'd need to find some sort of solution that could appease both parties- the ones who wish to see the chat free of spam and lrrbot free of "bloat", and those that find that find the !quote functionality entertaining, and wish to see it stay.

There's been talk in the past of having lrrbot whisper something along the lines of "this command is on cooldown, try again in X seconds" or even whispering the quote itself to the user using !quote, but as I have learned from other issues MrPhlip's page, this will not feasible until Twitch introduces their new system, and even then, how difficult such implementation would be is currently unknown. 

Personally, I feel that this would be the most straightforward solution. Alas, it is inaccessible to us while the problem still remains. I have a few ideas of what we could do in the meantime, though I confess they may take a bit of effort to fully implement. However, I believe that should we succeed in such implementation, the novelty of the Quote system shall be preserved while simultaneously keeping LoadingReadyRun's chat healthy. 

If you'll recall back to the early months of LoadingReadyLive, while Season 11 still ran, some of the frequenters of the LoadingReadyRun wiki designed a quotes page for the streams, as seen here: http://wiki.loadingreadyrun.com/LoadingReadyLive_Quotes

I propose that we redesign the Quotes system to direct viewers to the quote database, and design the database to mirror the old LRR wiki quote page. I propose a redesign as opposed to a redirect to the wiki for 2 reasons. Firstly, as is evident by the page, the LRR wiki's quote page is no longer maintained. There are several months worth of streams missing at this point. Secondly, lrrbot's quote database is already in a working order and could feasibly be redesigned to surpass that of the old wiki page. With this, people could browse quotes at their leisure, without subjecting the rest of the chat to said quotes. It reduces spam, cleans the chat up, and still lets people get their laughs in. In terms of the redesign, the current format of quoting seems suitable. In the future, I feel that the quotes should also contain the game that was being played at the time. Is there a way to get lrrbot to pull this automatically since it has the !game function? It may also be wise to include the show but I'd imagine the game's more important and would make the need to list the show redundant. Just as an example a quote would feature: (Name of person who said quote)(date)(show/game title) "Quote". lrrbot's database would then need to be able sort quotes by name, date, show/game title, and perhaps the actual content in the quote.

With respect to how to use the new !quote command, I feel that !quote should be either Subscriber or Moderator only. The new !quote command would simply redirect users to the database, rather than spitting out a random quote or a specific quote based on designation. Giving the command to only subs or mods would deter the randoms from spamming the command, and would technically not even limit the quotes to subscribers, as one could hypothetically just access lrrbot's database by having the URL.

Thank you all for taking the time to read this, and let me know how others are feeling and thinking about this issue. Hell, it may not even be an issue at all in your minds!

**Comment by d3fr0st** [comment]
Making it sub only might be a pretty solid solution I could always combine that with a dynamic cooldown as in #32

**Comment by andreasots** [comment]
(I've just arrived from assembling supermarket shelves for 13 hours so I've just skimmed that huge blob of text. I'll reread it in the morning and come up with something more coherent.)

I'm quite comfortable having the `!quote` family of commands as is (as in they are commands that I think LRRbot should have) but agree that the current throttle mechanism is insufficient. I have to check the [logs](http://qrpth.eu/prism/) but I don't think making `!quote` sub-only is going to be enough. I wonder how much having a custom "`A similar command has been registered recently`" message that points to the quote database would help.

Some random sentences I picked up:
> With this, people could browse quotes at their leisure, without subjecting the rest of the chat to said quotes.

Like the [current quote database](http://lrrbot.mrphlip.com/quotes/)? Actually, I wonder how much of the `!quote` spam is because reading the quote database would take their attention away from the stream and chat and how much is because the chat doesn't read LRRbot's help page. There's a command named `!qdb` that might be helpful.

> In the future, I feel that the quotes should also contain the game that was being played at the time.

We have >500 existing quotes without game information and some that can't have game information (podcast quotes). 

> lrrbot's database would then need to be able sort quotes by name, date, show/game title, and perhaps the actual content in the quote.

Issue #90.

> The new !quote command would simply redirect users to the database, rather than spitting out a random quote or a specific quote based on designation.

So the new `!quote` would be the current `!qdb`? So let's call it `!qdb`.


I should stop looking at this laptop now.

**Comment by d3fr0st** [comment]
Honestly I'll try to get #32 done tonight, as soon as I'm back from work.  Also as soon as we can get whisper working we could also give the users what their cooldown is, and have a mode where the reply is a whisper itself similar to !subonly. 

My only issue with #32 is that it will slow down the bot as it'll need to call the api for viewer amount for each reply...

**Comment by d3fr0st** [comment]
I'm sure we could find a couple of people willing to add game information if we were going to go that way though it'd be quite a project. 

Can't edit comments from phone...

**Comment by mrphlip** [comment]
Some random thoughts:

I've re-examined the possibility of adding whisper functionality to the bot, and I think it would be doable. The main concern is that we've been told the current setup is only temporary, and no idea when it'll change. Also I can't work on it right now with my Internet situation.

I don't think that dropping `!quote` in favour of the qdb page isn't a tenable idea... Like, that page already exists, you can already browse the quotes... just like you can already see random advice on every page, and see what is occasionally a complete list on the wiki. Yet `!quote` and `!advice` are probably the most commonly used toy commands on the bot. There's something about hearing a joke in public that's more fun than in private.

I'm still not super convinced that #32 will work... We've tried tinkering with the cooldown, I'm not convinced that's the real problem. That said, you wouldn't need to be making constant api calls to get the chatter count, just turn on the join/part cap req, and get the user count from `len(bot.channels[event.target].users())`

Finally, about adding game/show data to quotes... I think that makes sense. Retrofitting old quotes would be a job, but they're dated and we have foxmar's spreadsheet, so not impossible. We want to be careful about adding too much context to some quotes, since for many part of the humour is that they're out of context, but game/show is probably fine.

I think we'd want to make it so that if you leave off the date from the `!addquote

**Comment by andreasots** [comment]
> I have to check the logs but I don't think making `!quote` sub-only is going to be enough.

I was wrong. Numbers:
```
Current: 3356
        Got response: 2789
        Ignored: 567
If made sub-only: 1313
        Got response: 1105
        Ignored: 208
If made mod-only: 343
        Got response: 342
        Ignored: 1
```

**Comment by AdmiralMemo** [comment]
I was the one who maintained the Wiki Quotes page, but I got heavily back-logged and then Twitch messed up my system by making the past broadcasts inaccessible, so I gave up, hoping someone else would take up the mantle. It appears they did not.

Speaking as a moderator and as a fan of the !quote command, I do think throttling is necessary. It's way too spammy. Is there a way to throttle the !quote command without arguments separately from the one with? It's the random quotes that get the most spam, I've seen, rather than things like !quote 188 or !quote James and such.

Also, I think making it sub-only seems like a good step, after seeing the numbers.

One thing I noticed about the !addquote command is that syntax is very finicky. Is there a way to avoid that, as maybe only 2 or 3 of the Mods really understand the syntax? For example "!addquote (James) [now] This is a quote." gets what you want, but "!addquote [now] (James) This is a quote." puts the (James) part into the quote itself.

**Comment by andreasots** [comment]
> Is there a way to throttle the !quote command without arguments separately from the one with?

Wouldn't that increase `!quote` spam? The number of quotes posted within a timeout period would increase from four (two from `!quote` and two from `!findquote`) to six (four from `!quote` and two from `!findquote`).

> One thing I noticed about the !addquote command is that syntax is very finicky. [...] For example "`!addquote (James) [now] This is a quote.`" gets what you want, but "`!addquote [now] (James) This is a quote.`" puts the (James) part into the quote itself.

Can't accept both as it'll make the grammar ambiguous.

**Comment by AdmiralMemo** [comment]
Fair points.

**Comment by andreasots** [comment]
>> One thing I noticed about the !addquote command is that syntax is very finicky. [...] For example "`!addquote (James) [now] This is a quote.`" gets what you want, but "`!addquote [now] (James) This is a quote.`" puts the (James) part into the quote itself.

> Can't accept both as it'll make the grammar ambiguous.

[`19:13 AdmiralMemo: Lord_Hosk, Just for reference, you don't need the quotes when entering it. :-)`](http://qrpth.eu/prism/log?start=1436338800.0&stop=1436425200.0#entry-2594195)

It's possible to accept `!addquote (James) [now] "This is a quote."` and `!addquote [now] (James) "This is a quote."` or even `!addquote "This is a quote." [now] (James)`. It's technically still ambiguous but whatever the order of the individual parts it would still be parsed correctly.

**Comment by Compleatly** [comment]
Speaking to the earlier mentioned issue of curating the quotes page to add shows, game titles, (and maybe even context where applicable?) I'd personally be willing to aid in that endeavor. Considering that this is the same community that produced the DB gif team and the DB Video Strike Team, I imagine that opening such a task to select volunteers would make feasible.

**Comment by d3fr0st** [comment]
Also what about a global cooldown, similar to the counts?
