### ISSUE TITLE
LRR channel in the !live command

### ISSUE THREAD

**Issue by AdmiralMemo** [mrphlip/lrrbot#121]
I've noticed that LoadingReadyRun keeps coming back into the list of !live channels for some reason. I've seen various of us repeatedly remove it, because it's supposed to be just for FAN streams, right? I don't know why it keeps coming back. Can someone check the logs? Is someone doing this specifically? Or is something malfunctioning and adding it back?

**Comment by mrphlip** [comment]
It automatically adds any channel that's on the fanstream calendar... which means it's probably adding the main LRR channel because of [this](https://www.google.com/calendar/render?eid=Y200bjFvYmphbHBrZ2E2cmRraGdiMnNpbTBfMjAxNTEwMjhUMjEwMDAwWiBjYWZmZWluYXRlZGxlbXVyQG0)...

Maybe we can do some processing that users who have been manually removed don't get automatically re-added? Or just special-case that the bot won't follow `loadingreadyrun`?

**Comment by AdmiralMemo** [comment]
Or we could just get Lemur to edit that to twitch.tv/voxlunch
