### ISSUE TITLE
Disable death count for ASTC

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#184]
So, apparently Cam doesn't want us tracking deaths on his stream. Which is entirely fair.

I haven't caught up on his latest stream, so I don't know all the details... Is this just for certain games, or all of them? And should this be retroactive, removing death counts from old ASTC games? I'm guessing "all of them" and "Cam hasn't said", but if someone who's watched the stream wants to chime in that'd be great.

TStodden emailed suggesting a `!death toggle off` command that disabled death count for a particular game, but if it's a blanket "don't count ASTC deaths"  then might just want to handle that automatically.

So,what I'm thinking is... we want a central function in `common`, something like:
```
def should_track(game, show, stat):
  return show != 'astc' or stat != 'death'
```
so the logic is all in one place, so it can be changed easily in the future (possibly having a per-game flag later if needed). Then this would have the effect of:

* Using `!death`,  `!deathcount`, etc would give a notice that they don't apply.
* `!totaldeath` would ignore the game.
* `/api/stats/death` would return `-` (or possibly `-1` which is the current joke value).
* The stats webpage would just show a `-` in that cell of the table. When every game in the table doesn't show a given stat (ie when you're on the ASTC page) just remove the column entirely, and don't show that pie chart.
* Anything I'm missing?

**Comment by AdmiralMemo** [comment]
He doesn't want deaths, tilts, or paves tracked at any time on his stream, from what I've heard.

And he hasn't said anything about retroactive.

However, I KNOW we haven't been consistent about what counts as a !death in XCOM anyway, because I've seen times where squad death = !death and other times where single death = !death
Therefore, if they do end up being completely removed, it won't be a total loss, since it was never accurate for any definition of accurate anyway.

Automatic handling would be good... Like, we could turn off !death in any of the MtG games and such.
