### ISSUE TITLE
Additions/Changes for the new Streams

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#199]
Hey Folks,

As you know, we are going to be changing up the stream schedule during May, retiring many of the current shows, debuting a bunch of new shows and shuffling the schedule around. As part of this we are also going to be doing a style refresh on the overlays for many of the streams. After talking about it internally, there are a few things we are hoping to do with the new overlays that would benefit from LRRbot integration, so I wanted to get your feedback on what is possible and how much work it would take.

1. Separate storm count for new subs vs resubs
2. Include storm count with the new subscriber notifications (so that we can increment a number on screen as part of the notification
3. For AFK and other streams where we don't use the notifier, some way to query LRRbot for the list of subs since the stream has been online (or since a certain time) so that we can show them on the screen while we do the batch sub welcomes after commercials.
4. LRRbot tracking and notifications for Follows as well as subs (TwitchAlerts is ok, but it would be nice to have the notifiers "in house" and allow for more customization)
5. Maybe just a different use of the !highlight command, but a way for the chat to mark cool/fun things that happen during the stream which could then be accessed by one of our editors to speed up the process of finding clips for a "best of" highlight reel for a given stream. Ideally the listing of highlights would have video-relative timecodese (instead of clock-relative). Probably mostly used with special events and AFK streams like the SOI preprerelease.

Thanks again for all your awesome work on LRRbot! I think it really adds to the LRR stream viewer experience.

Cheers,
Paul

**Comment by mrphlip** [comment]
My quick thoughts:

1. Sounds pretty simple. One question is, if there's a new sub, would we show just the new-subs count, or both, in the welcome message in chat? And similarly for resubs. I think both, but would have to come up with something that seems good. Also, very occasionally, the streamer will read the wrong number, and say "Thanks for subscribing for X months!" when X is actually the storm count, because they read it from lrrbot's welcome message... I've occasionally considered echoing the subscription length in the welcome message too, and this would be a good a time as any to do that.
2. You mean, in the SSE channel? Makes sense, that can be added pretty easily. While we're doing this, we should move `www.notifications.new_message` from the webserver to lrrbot proper... it hasn't needed to be in `www` for a long time, just haven't had any reason to change it.
3. You can do this by getting the `key` latest notification at a certain time, then later you call `/notifications/updates?after=key` to get all the notifications since that time (the lrrbot website polls this to update the `/notifications` page if SSE isn't available in the browser). This is probably better than us adding a parameter to pass a timestamp or something, as it makes sure that the different ranges don't overlap - even if someone subs at about the same time you're loading the list, they'll either be in that list or the next one, never both or neither.
4. Sure, we can do that. Basically the same as the subscriber polling we already do (to catch new subscribers when the in-chat notifications are broken for whatever reason). [Relevant doc](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-channelschannelfollows)
5. That sounds... pretty much identical to what the `!highlight` command already does... it adds to [this spreadsheet](https://docs.google.com/spreadsheets/d/1yrf6d7dPyTiWksFkhISqEc-JR71dxZMkUoYrX4BR40Y/edit) (with video-relative timecodes).

**Comment by AdmiralMemo** [comment]
Regarding #5, it's currently subscriber-only. Did you want to change that? (I think we have enough subscribers, though, that even if a non-sub really wants a highlight, a sub could relay that command.)

**Comment by AdmiralMemo** [comment]
Also, whoever's doing the sheet... it's 2016 now, not 2015, so I think we need a new tab.

**Comment by paul-lrr** [comment]
It is nice when most of the feature requests are actually already in place ^_^

I think it would be good to show both the new/resub count as well as the overall sub count
Sending the Follows through the same channel as the subs seems fine. If I understand correctly this means that the json sent when there is a new sub/follow will have a few more fields: New Sub, Resub or Follow, Patreon or Twitch, and  new sub and resub count. If I have that info, it should be straight forward for me to format the various messages differently.

**Comment by andreasots** [comment]
I want to move the subscriber and follower notifications that the overlay uses into separate events from `"newmessage"`. Something like `"subscriber"` for Twitch (re)subs, `"patron"` for Patreon and `"follower"` for Twitch followers.

About Patreon: do you want a resub mechanism? Do you want the pledge amount? Do you want to be notified when a pledge is changed? Deleted? Do you want to not be notified when a pledge is deleted and recreated? How much information do you want about the backer from both Patreon and Twitch?

**Comment by paul-lrr** [comment]
I don't think Patreon resubs are necessary. Notification of pledge changing might be good, but we would only use it for *increasing* pledges (and even then, maybe not). By the same token, we wouldn't be displaying deleted pledges. Hopefully people deleting and recreating their patreon pledge won't be too much of an issue, but if it starts being a problem, I guess we will need some way to limit that. We wouldn't be displaying the pledge amount either. The backer information we need is really just the username of the person, the type of sub (new, resub or patreon) and the number of months for resubs.
