### ISSUE TITLE
New show codes

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#205]
Sorry I didn't get these to you guys earlier, some of the stuff for the new shows took a while to nail down.
```
Rhythm Cafe -> rhythm
Tinker, Tailor, Solder, Fry -> tinker
New Day Tewsday -> newday
AFK -> afk
Talking Simulator -> talkingsim
Matter of Import -> import
Bonus Stream -> bonus
```

**Comment by mrphlip** [comment]
Thanks for the list. That leaves 18 Games and LoadingReadyLive, do those have codes?

I added LoadingReadyLive as `lrl` during the stream yesterday so that I could `!show override` it... the code was just a placeholder for if the show has a real code. It didn't look like the fancy LRL overlay was calling the set show API call...

**Comment by paul-lrr** [comment]
Right! Let's do:
```
Loadingreadylive -> lrl
18 games and counting -> eighteen
```
I will try to make sure the new overlays (including LRL) call the set show API

**Comment by andreasots** [comment]
New shows added.

**Comment by AdmiralMemo** [comment]
The show apparently needs to be overridden each time for now because something is stuck on New Day Tewsday.
