### ISSUE TITLE
Resubs from the API are displayed as a new sub

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#206]
![sub-bug](https://cloud.githubusercontent.com/assets/104879/15473931/2c6cef22-210b-11e6-869e-3cb4cad8f366.png)

**Comment by mrphlip** [comment]
Potential solution: when new subscribers are seen by the api poller, have it `loop.call_later` the actual notification code after some amount of time (a minute maybe? look at how much lead time there's ever been between lrrbot's welcome and the twitchnotify in the past, and add a buffer to that). Also make it so that the notification code checks for duplicates within a certain amount of time (make it a twice as long, for safety), rather than what it currently does, which is check for duplicates within the last 10 subs.

That should make it so that, when it sees a new sub in via API, it waits a bit for twitchnotify to do it properly, and use that... and only use the details from the API call and assume it's a new sub if twitchnotify says nothing.

**Comment by andreasots** [comment]
Fixed in master.

**Comment by andreasots** [comment]
Currently subscribers from the API are delayed by 60 seconds. This is not enough and in fact no reasonable delay is enough as there are resubs that fire 18 hours after they appear in the API.

**Comment by mrphlip** [comment]
It now seems that, with resub messages, the flow is now: user's sub lapses, they disappear from the API sub list, they re-subscribe within the window, re-appear in the API sub list immediately, but then they also get the prompt to send a resub message, which obviously doesn't appear in chat until they actually decide what to enter and send it.

So there can be an indefinite time between someone re-subscribing a recently-lapsed subscription and the resub notice in the chat.

I don't think that there's a good solution to this short of disabling the API check entirely.

Which... now that I think about it, would that be so bad? The whole API check was a patch around a time when Twitch would sometimes just fail to mention a new sub in the chat, and I don't think I've seen that happen in some time... but then, maybe it is still happening and I just never notice because we rely on lrrbot to do our sub checking for us, and don't look at the twitchnotify messages? Hmm...

**Comment by andreasots** [comment]
Let's remove it.
