### ISSUE TITLE
Database backups

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#207]
Currently, there's a cron script that makes copies of `data.json` every day, but now that most of that data has been moved into the DB, that's not as useful... we should be making regular `pg_dump`s of the DB contents for safety.

**Comment by mrphlip** [comment]
Also, it looks like even the `data.json` backups haven't been happening since the server move... New server doesn't have `crontab`, it looks like? I don't know what the replacement for that is, but we should do something...

**Comment by andreasots** [comment]
[Continuous archiving](https://www.postgresql.org/docs/9.5/static/continuous-archiving.html) of the database and daily `data.json` backups have been running since 2016-05-15. I wrote a tool named `archiver` to do deduplication, compression and uploading. `archiver --help` will give you all options it accepts.

> New server doesn't have `crontab`, it looks like? I don't know what the replacement for that is, but we should do something...

Replacement is [systemd timer units](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) or `crontab-systemd`.
