### ISSUE TITLE
LRRbot instability

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#221]
It is a testament to how great LRRbot is that we have come to rely on it for a lot of stream functions, including very important stuff like sub notifications, next stream information and highlights as well as fun stuff like quotes, mtg cards and advice. After working very reliably for more than a year, LRRbot seems to have been experiencing quite a few stability issues in the last couple weeks, with it going down for large stretches until someone is able to restart it. 

I'm sure you folks are working on whatever issues have crept into the system but I was wondering if there is anything we at LRR can do to help. Do you need more Devs? a better server? LRRbot is useful enough that we would be willing to pay for a new server, if that would help make it more reliable.

**Comment by d3fr0st** [comment]
So I haven't actually develop anything for LRRBot in quite a while because of time constraints (just graduated college) and most of the stuff these 2 are doing is way beyond me. I try to stick around giving the bot a kick when it's down. That said the server seems to be fine and looking through the logs I didn't see anything that'd make the bot crash.

The bot as far as I remember didn't log any errors but it just stopped responding... I'll try to look back on the logs when I get back home though I have a feeling the problem might be from some change twitch did.

**Comment by andreasots** [comment]
> Do you need more Devs?

We don't have enough contributors to keep things moving at a reasonable pace. Writing down set-up instructions and making a forum post with a poorly photoshopped propaganda poster is in my ever-growing list of things that should have been done like a month ago.

> a better server? LRRbot is useful enough that we would be willing to pay for a new server, if that would help make it more reliable.

Thank you for the offer but the current server is more than fine.

**Comment by d3fr0st** [comment]
> a poorly photoshopped propaganda poster
That is something I can actually do :P

**Comment by mrphlip** [comment]
> We don't have enough contributors to keep things moving at a reasonable pace.

Yeah, I haven't been able to find time to work on the bot for a long time... qrpth has basically been maintaining it solo. And he's done an amazing job, but there's only so much one person can do...

**Comment by paul-lrr** [comment]
If we were to put a call out for people to assist with LRRbot development, what skills would they need to have?

**Comment by mrphlip** [comment]
Since #223 and related fixes, the instability problem seems to be well in hand, we haven't had nearly as much of a problem with the bot staying alive. So closing this.
