### ISSUE TITLE
Names of storm counts

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#228]
1. Come up with real names. No, that one doesn't work because it doesn't scan.
2. ~~Remove combining characters from randomly generated ones because people are getting timed out for using them.~~

**Comment by mrphlip** [comment]
Also: could be worth combining the new-subs and re-subs counts into a single counter (for display at least, even if they're counted separately behind the scenes). People seem to get confused that the counter in chat doesn't match the counter on-stream.

**Comment by mowdownjoe** [comment]
Suggestion for the resub name, because I don't feel "delirium" actually fits... devotion, maybe? I don't like delirium because it isn't something you count, but rather it's a state. Devotion fits with resubs and it something that is counted in Magic.

**Comment by AdmiralMemo** [comment]
+1 Devotion

**Comment by ka13b** [comment]
If you're thinking of a magic theme, then lifelink could work for either new subs or patreon.

**Comment by mrphlip** [comment]
Looking though some lists of Magic mechanics, here's what I've come up with. Probably not a complete list, but w/e.

Counting mechanics:
* Affinity
* Converge/Sunburst
* Devotion/Chroma
* Domain
* Gravestorm
* Storm
* Suspend
* Vanishing/Fading

Threshold mechanics:
* Battalion
* Delirium
* Metalcraft
* Spell mastery
* Threshold

Many of these don't work as "x count" (eg you don't have an "affinity count", you just have a number of artifacts), and many don't work for this purpose (eg Suspend/Vanishing/Fading all count _down_, or Domain has a maximum count and is also boring).

So I think the realistic options are:
* Devotion
* Delirium
* Storm
* maybe Battalion, but I'm not a huge fan

Really, "storm count" is a pretty unique fit, in that it's it's a count of events that happen over the course of a turn (or day), that you'll usually count aloud as they happen... that counts up over time and the higher it gets the better, and the aim is to get it well into the double digits. All of which pairs up with the sub count quite nicely. None of the other counters really work in the same way.

Of course, there's nothing to say that we need to stick to Magic terms. The "storm count" slang originally came from a magic stream (I stole it from Doc, I dunno if he came up with it or he got it from elsewhere), but LRR hasn't been a Magic-only stream for years, so other things could be relevant. Surely there are other injokes we could use.

**Comment by MatthewCox** [comment]
How about Keys Collected? (Watch+Play/Let's Nope)
Struggling to think of any other injokes that involve counts of things.

**Comment by RebelliousUno** [comment]
So I originally came up with Delierium during the EMN stream.  While it's not technically a "count" in the game people do say "My delierium count is 3" etc.
I considered the idea of devotion but I would think that more for patrons.  That could also just sit at devotees.

What I think we should try to do is shy away from specific terms and be more generic with the terms, since I don't think we've got any LRR Specific In Joke counters, and just settle on something that makes sense to people who are not familiar with Magic (and potentially new to LRR as a whole)

**Comment by RebelliousUno** [comment]
Though if you were to go on a video game count (which lets face it is what the streams are largely about) 
Something around X Hit Combos (from beat-em-ups).

**Comment by cecilemuller** [comment]
How about something like "Fever"?

**Comment by AdmiralMemo** [comment]
If we do have MtG-related counters, I'm liking Devotion for the resubs, while Affinity, Tribute, or Cumulative Upkeep could work for Patreon.

**Comment by andreasots** [comment]
I like the idea to have the counters be from different games and/or genres. In particular I like 'combo count' for resubscriptions.

I don't like 'devotion'. It feels extremely weird to me.

**Comment by mrphlip** [comment]
The more I think about this, the more I think we just don't need fancy joke names for all these different counters. We obviously can't come up with them, anyway.

The `!storm` command should just output all the various counters without trying to come up with a name for each one. Meanwhile, the "thanks" message to subs and patrons should just say "storm count", and the number there should be the sum of the new-sub, resub and new-patron counters.

Then the "storm count" that appears in the chat will match the number on the storm cloud in the overlay, and we just have one weird incomprehensible injoke term, instead of half a dozen.
