### ISSUE TITLE
!highlight makeover

### ISSUE THREAD

**Issue by SniperPumpkin** [mrphlip/lrrbot#239]
When something wort highlighting happens on stream, often two or three people will attempt to highlight within a few seconds. In general, the person who types the shortest, least descriptive comment will be the first to issue the command in chat.  !highlight is limited to once per 30s, so any longer or more descriptive entries are lost.  This can create issues with the person who is trying to find the incident can't determine what was intended.

Suggested fix:
When multiple !highlight commands are issues in a short window (10-20s?) combine all of the descriptions and apply them to the spreadsheet as a single line.

**Comment by d3fr0st** [comment]
I'll ask foxmar about this as he's the one that typically does the highlights but for me at least I don't feel it would help me when I end up doing some.

**Comment by andreasots** [comment]
Secret Slack discussion:

> **d3fr0st5**: @​foxmar320 Is https://github.com/mrphlip/lrrbot/issues/239 something you'd be interested in?
> **mrphlip**: I've occasionally considered if there's something we can build that would be more useful than the "just cram it in a googledoc" method, and that is definitely one part of what I've thought about...
> **foxmar320**: It could help. Sometimes I get such helpful descriptions like "wut" and "lol"
> **foxmar320**: But whatever is easy for you guys.
> **d3fr0st5**: Honestly the whole highlight system right now seem like something we could do better, it works but that's about it...
> **foxmar320**: Yeah

**Comment by mrphlip** [comment]
Like I said, I've thought about this a bit... I've only done highlighting a couple of times, but from what I've seen the Twitch highlighter page isn't very good. Chief among its problems:
* You can only create one highlight. Once you've done that, you need to re-load the page, which re-loads the video, which wastes time and makes you lose your spot.
* The "start" and "end" position handles on the timeline get in the way of your ability to actually click on the timeline and seek the video playback, making it impossible to quickly seek to the ends of the clip and check they're in the right place. Clicking and dragging the handles moves the playback to where you dropped the handle (but moves the handle, so you can't really use that for checking your work) but simply clicking the handle instead seeks the playback to the beginning of the clip (likely a bug).

I've thought a bit about what can be done to improve this. There isn't a Twitch API call to make a highlight, unfortunately, but from what I've read online the internal API call the official page uses isn't particularly complicated, so we could probably piggy-back onto it without too much difficulty... with all the usual caveats of relying on undocumented interfaces, plus the fact that I haven't actually checked myself. So we could make our own mod-only page that embeds the video (like `/archive`) and lets you make highlights.

Some features I'd consider:
* Record highlights in our own DB table, rather than the google doc. Link them against the stream they came from, as we already do. Have a status column with options like: Unconsidered; Created; Maybe; Deleted.
* Get rid of the rate limiter entirely (but rate-limit the "Highlight added" response, to avoid spam). If 5 people respond to the same event, just have it five times in the result. For version 2 we can consider visually collecting entries that happened at about the same time together.
* Highlighter loads up a video. It has the synced chat next to it, in case there's anything in there that helps them locate the clip.
* It also pulls up _all_ the marked highlights from the chat for that video. You can pick which one you want to work on, it automatically picks the first one in the list when the page loads. It automatically seeks to some period before the `!highlight` command (I previously guessed about 30-45 seconds... 15 seconds for chat lag, 5 seconds for chat reaction time, 10-30 seconds for how long the actual thing that happens is).
* Let the mod mark out a start and end time for the highlight. Have a "preview" button that seeks to the start handle, lets it play until it reaches the end handle, then pauses playback, so the mod can check the bounds are right. Perhaps for longer highlights, have it play like the first and last 10 seconds.
* Then the mod can submit the highlight to the undocumented API call... it would default the description to the one from chat, but let them edit it first. Then it records the highlight URL in the DB (just in case), and moves on to the next entry, without having to reload the page.
* Alternatively, the mod can decide _not_ to create a highlight for a given entry, and just delete it (by which I mean, set the status to "deleted"). Or they can mark it as "maybe" to basically mean "I dunno, I'll come back to this later".
* For the purposes of coordination, if one mod opens up a particular video, then when another mod tries to open the same video, it would give them some sort of warning. I know I've seen it when foxmar was doing highlights on-stream, and another mod was also doing it at the same time, and they started working on the same vid, it got a bit confusing.

**Comment by AdmiralMemo** [comment]
If this could happen, I know I would start helping out with the highlighting duties. One of the reasons I don't is that I totally hate the Twitch highlighting system as it currently is.

**Comment by d3fr0st** [comment]
Everyone does... it's a garbage system that twitch forgot about 3 years ago. 

@mrphlip That sounds like a great system, I've got 2 concerns with it though, The first being the recent changes to twitch player (html5) which don't seem to be global yet, and might change how we interact with the player. The second being that it would rely on the undocumented API which given twitch history could completely change with no notice at any time...

**Comment by mrphlip** [comment]
We've been using the html5 player on `/archive` for a while and it hasn't had any real troubles. As for the undocumented API... yeah, that's always going to be a pretty big concern, but I think if it's doable then it'd be worth it.

**Comment by andreasots** [comment]
The API request the video manager does with unnecessary parts removed:

```
curl 'https://api.twitch.tv/api/channels/<channel>/video_manager/<video ID>/create_highlight' \
    -H 'Client-ID: jzkbprff40iqj646a697cyrvl0zt2m6' \
    -H 'Twitch-Api-Token: <API token>' \
    -H 'Cookie: persistent=<persistent token>; api_token=<API token>' \
    --data 'start_time=<start timestamp in seconds>&end_time=<end timestamp in seconds>&title=<highlight title>&description=<description>&game=<game name>&language=<language code, probably ISO 639-1>&tag_list=<comma-separated list of tags>'
```

The API token and the client ID can be replaced with ours but the only way to get the persistent token seems to be to log in. The users who the tokens belong to don't seem to need to match. So we could have a throwaway account with which to generate the persistent tokens. Probably.

> For the purposes of coordination, if one mod opens up a particular video, then when another mod tries to open the same video, it would give them some sort of warning. I know I've seen it when foxmar was doing highlights on-stream, and another mod was also doing it at the same time, and they started working on the same vid, it got a bit confusing.

I think it would be less confusing if it was an error instead with the option of manually overriding it.

**Comment by mrphlip** [comment]
All of this is basically obsolete now that clips are a thing.
