### ISSUE TITLE
Now Kiss chat game decision

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#346]
Hey folks,
Kathleen would like to end her new Now Kiss show on a "swipe left or swipe right" Tinder joke, where the chat decides whether Kathleen continues with the game next week or finds something new. We were thinking it could be done by having people type `right` or `left` In the chat. Basically it would like the old !game bad/good thing except that we would actually use this😜.The two extra things would be that it should only be active at the end on the stream (probably when a mod turns it on with a command in chat) and I would need some sort of endpoint that returns the votes for each option that I can hook into to make an onscreen graphic.

Do you think that is something that would be possible?

**Comment by mrphlip** [comment]
I've thought about adding polling functionality to lrrbot before, and we _could_ do it... but I've wanted to avoid making anything that does polls in-chat, as it tends to make actual chatting basically impossible. Like, you've played Choice Chamber, you've seen how it gets. And sure, this wouldn't be as bad as that, but still.

So I figured if I wanted to implement polls in lrrbot I'd want to do it on the website. And then I figured I wasn't going to be able to build a website that did it _better_ than strawpoll already does, so may as wel just use that instead...

Now, we could just make a shortcut for `!poll 300 Now kiss?: Swipe left, Swipe right` or whatever that Kathleen can use to make the strawpoll. But the functionality is already in there.

Unless you had a preference for this being done in-chat rather than with strawpoll?

**Comment by mrphlip** [comment]
Though, a thought that we could have an api endoint to get the active strawpoll ids, or maybe a new event in the SSE channel when a poll is added, something that the overlay can watch to see when a poll is created, so all the host would need to do is run the chat command, and hit a button in the overlay, and not have to manually copy the strawpoll id from chat into the overlay...

**Comment by RebelliousUno** [comment]
Is there something that could be done with the twitch extension API for
interactive overlays?

**Comment by cecilemuller** [comment]
How about also displaying the results of the strawpoll in a stream overlay, with the color/branding of the show ? (or is the poll meant to run only after the show has ended ?)

**Comment by paul-lrr** [comment]
Displaying the strawpoll results on the stream with a custom graphic was my thought as well.  Graham was thinking of chat voting to make it as simple as possible for viewers to participate (with the idea that the chat spamming would only happen at the end of the show). I think the strawpoll is probably the way to go, at least to start with. The idea of having the strawpoll id available as an api endpoint or a SSE would definitely make things easier for the streamer.  

Another factor is that if people are watching but _not_ in chat, they might be more inclined to vote in a strawpoll rather then boot up the chat and login to twitch. I'm pretty sure we have done polls where there are more votes then active chat users.

**Comment by paul-lrr** [comment]
@RebelliousUno The idea of using the extension API to display the results is interesting (I think there may already be a poll overlay) but I feel like it is probably best to go with real on-screen graphics for now. For one thing, I'm pretty sure extension don't work for mobile/console viewers.

**Comment by cecilemuller** [comment]
I looked some more into Twitch Extensions and it seems kinda annoying to develop for, like you have to do [two interviews for tax infos](https://dev.twitch.tv/docs/extensions/onboarding) (which seems overkill for a free extension for one specific streamer), so something that integrates directly  to OBS (or does LRR use Xsplit, I always forget) sounds simpler, especially if extensions don't even work for mobile/console users.

**Comment by mrphlip** [comment]
@paul-lrr OK, so I've added a few things.

First of all, I've added the command `!nowkiss` which is essentially just a shortcut for `!poll 300 Now Kiss?: Swipe Right (yes); Swipe Left (no)`, ie creating that poll on Strawpoll and adding it to the bot so it'll report the result in chat in 5 minutes. We can easily change the exact wording or the timing if you (or Kathleen) would prefer.

Next, I've added events to the SSE channel - `strawpoll-add`, `strawpoll-complete` and `strawpoll-clear`. The body for `strawpoll-add` and `strawpoll-complete` is essentially just the data we get back from the Strawpoll API... however, if the poll was created with `!nowkiss` I've added a `tag` field which says so (if the poll was added normally, this field won't be present), so that the overlay can use that for distinguishing `!nowkiss` polls from other polls. So the body looks like this:
```

**Comment by paul-lrr** [comment]
Spiffy! Something matching the poll from the last stream would be ideal. Since the polls will be almost the same each week, I put the date in the title so that people know they are voting in the right one. Having the Game in there as well would also help. As you might guess, all I really need is the poll id (since my script grabs the rest of the data through the strawpoll api), but the `tag` field will be handy to separate things. 

I don't think there are current plans, but if we want to have polls associated with other shows, I guess we could just have the `tag` field always be the show id of the current show.

**Comment by mrphlip** [comment]
OK, I changed the wording so now it looks like [this](http://www.strawpoll.me/14014204) with the game title in the question (assuming it exists in Twitch or someone sets the game override in lrrbot... if it's just set to "Games + Demos" then it'll leave the game title out).

I figured all you'd probably need is the poll id, but I figured, we already have all this other info handy anyway, no harm in throwing it in too.

The idea with the `tag` field is that it lets the overlay easily know whether the poll was created by the `!nowkiss` command or the normal way... so you could, for example, make it automatically show the poll overlay for `!nowkiss` polls without automatically showing an overlay for other polls. The overlay can also assume there's two poll options, and which order they're in, etc.

**Comment by mrphlip** [comment]
Seems to have been working!
