### ISSUE TITLE
Replace MySQL with PostgreSQL

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#74]
1. MySQL is toilets: 0de144da2fe1ddaf14ee9e5f7741107d1576bc51 c606bbddcd531c583fef7760ad88913eac590e00
2. MySQL as it's currently configured on the server can take up to 150M of memory and I have run out of ideas to lower it. On my laptop I have a default PostgreSQL install with a couple of weeks old LRRbot data dump and I can't make it use more than 60M of memory. This is test actually in MySQL's favor as the PostgreSQL server has about 20 active connections each taking about 1.2M of memory.

**Comment by mrphlip** [comment]
Oh god, yes, this so very much. Much like #35 etc, it's using MySQL purely because that's what NFS.net has to work with. MySQL is a misery, and I'm more than happy to burn it down and never look back.

I've never actually used Postgres (Firebird is my usual DBMS of choice)... I could probably muddle through it, but if you're familiar with it and can get it working, then go nuts.
