### ISSUE TITLE
LRRbot Chat Logs Stopping

### ISSUE THREAD

**Issue by AdmiralMemo** [mrphlip/lrrbot#80]
The chat logs on the VODs seem to stop with some regularity. Is there a specific reason they're doing that, or just random things pop up?

**Comment by mrphlip** [comment]
I believe the problem was that someone would go to the VOD page at some point while the stream was live (particularly common with Checkpoint), and the info it would get from Twitch says that the stream was pretty short (because that's all there is at the time)... and then it would cache that for a long time (24 hours), so even after the stream ends, the VOD page is still behaving as if the stream is much shorter.

I've significantly reduced the cache timeout from 24 hours to 5 minutes (there was really no need for it to be that long anyway... honestly Twitch could easily handle the load if we had no caching at all, I just want to be nice to their servers where possible), so this should stop happening now... do point out if you see it happening again, where the chat is cut short on a VOD long after the stream finishes.
