### ISSUE TITLE
Command Spam

### ISSUE THREAD

**Issue by AdmiralMemo** [mrphlip/lrrbot#99]
Some of Chat has been discussing the spamming of LRRbot commands and wondering what could be done about it. Changing timeouts and limits only goes so far. However, one thing that we thought of is that some people spam the commands because they think the command is broken, when LRRbot flat out doesn't respond. Would it be possible to have LRRbot whisper to someone who used a command that was over the programmed frequency that they're sending commands too fast and to please wait and try again?

**Comment by andreasots** [comment]
LRRbot won't have whisper support until Twitch moves to the new system or until I've figured out what is in scope of The Plan whichever comes first.

**Comment by d3fr0st** [comment]
Simply put, no. The whisper system isn't working with bots by design. We could try and rework the delay system but it seems mostly unnessecerly...

**Comment by mrphlip** [comment]
LRRbot has the ability to respond in-channel to throttled commands... it does for for !death et al. My theory was that having the bot respond with "Ye can't get ye command" to normal one-line-response commands isn't any *less* spammy than responding with the actual response, which is why it doesn't respond to those with that.

Per the discussion on #98, making the bot do whispers would be theoretically possible, but challenging, by design (and even if we did, the way whispers work is apparently subject to change).

**Comment by d3fr0st** [comment]
Agreed plus answering to commands telling them it's on cooldown won't stop people of spamming either way. Honestly my vote is to wait until this actually requires a fix from us or twitch implement their new system
